version: '3.8'

services:
  seller-db:
    image: postgres:latest
    container_name: seller-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: seller-db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5436:5432"
  app:
    build: .
    container_name: seller-api
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - seller-db
  cache:
    image: redis:6.2-alpine
    restart: always
    environment:
      - REDIS_PASSWORD=1234
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

volumes:
  db-data:
  cache:
    driver: local
