version: '3.8'

services:
  seller-db:
    image: postgres:latest
    container_name: seller-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: seller-db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5436:5432"
  app:
    build: .
    container_name: seller-api
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - seller-db

volumes:
  db-data:
